### ISSUE TITLE
bug: No longer tracking watch history on Android

### ISSUE THREAD

**Issue by VladoSkoko** [ReVanced/revanced-manager#1948]
### Bug description

Since patching the YouTube app with the latest version 10 days ago, the app has stopped recording the video watch history. The issue has appeared before, but it was patched soon after, so I decided not to report it immediately.

Steps to reproduce:
1. Play any regular video or Short from the homepage, search results, or otherwise.
2. Open the "You" tab and verify that the video does not appear under "History".
3. Open the same video again and notice that the play doesn't resume, but rather starts from the beginning.

I tried repatching and reinstalling the app.
I tried logging in again with microg.
I also tried using a newer version of the YouTube apk, but the patcher only allowed me to select 7 patches and it didn't let me install the apk.
I tried uninstalling the YouTube app and reinstalling the patched apk.
In all cases the issue persisted.

The issue is unlikely to be related to my account, as it worked before the latest patch and my history is tracked when watching videos directly on youtube.com.

I am unsure what was the previous patch version I had before installing the latest one.
[revanced-manager_logcat_20240613223122212961.log](https://github.com/user-attachments/files/15828574/revanced-manager_logcat_20240613223122212961.log)

### Version of ReVanced Manager and version & name of app you are patching

ReVanced Manager version: 1.21.0-dev.3
YouTube patch version: 4.9.0
YouTube apk version: 19.16.39 (per suggestion)

### Installation method

Regular

### ReVanced Manager logs

```shell
Attached as a file in the Bug description section, due to length.
```

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-X800
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: app.revanced.android.youtube v19.16.39 (Suggested: Any)
Patches version: v4.9.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 56 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installed
```

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [ ] The bug is only related to ReVanced Manager
