### ISSUE TITLE
[Tracking] improving docs

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-manager#953]
### Type

Other

### Issue

The docs have quite a few problems that needs addressing. This issue aims to be a centralized place for all of the issue so that we don't need to have like 10 small ones

### Feature

Edit the docs in dev

### Motivation

solve the issues in docs, improve readability, clarity and accessibility

### Additional context

- [ ] 1. Split APK can still be selected in the app list {2.1} 
  - Use storage whenever non-root is used 
- [ ] 2. emphasize split apk not supported {2.1} 
- [ ] 3. Patching time depends heavily on devices processing power {2.1} 
- [ ] 4. move the optional statement out of the grey text {2.1} 
- [ ] 5. add redir to troubleshoot page for patching issue {2.1} 
- [ ] 6. patching fails might also be non-supported arch {3} 
- [ ] 7. patching fails might be using split apk, redir to lower error code section {3} 
- [ ] 8. troubleshoot manager does not install {3} 
- [ ] 9. troubleshoot other reason that the patched app fails to install {3} 
- [ ] 10. troubleshoot 3rd party src related patching issue {3} 
- [ ] 11. troubleshoot "manager does not select apk" {3} 
- [ ] 12. troubleshoot "patch not found" {3} 
- [ ] 13. emphasize the need of microG for non-root install {3} 
- [ ] 14. troubleshoot microG related popup {3} 
- [ ] 15. suggest non-official resources revanced/revanced-documentation#19
- [ ] 16. GitHub mobile handles footnotes poorly, add a separating line at the bottom for compatibility

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] The issue is related solely to the ReVanced Manager

**Comment by oSumAtrIX** [comment]
Thanks for helping with documentation. 
Can you numerate the checkboxes so we can refer to them when discussing?

**Comment by xafn** [comment]
4. Refer to conversation here: https://github.com/revanced/revanced-manager/pull/911#discussion_r1212813953
Since it's not qualified to be its own step, how else would you suggest we format it like?

**Comment by oSumAtrIX** [comment]
The docs have been updated, please update this issue
